cauldrons:
  require-permission: true
  lower-water-level: true

effects:
  splash:
    particles: true
    sound:
      name: minecraft:ambient.underwater.exit
      volume: 0.75
      pitch: 1.0

  transform:
    particles: true
    sound:
      name: minecraft:block.deepslate.break
      volume: 0.65
      pitch: 1.25
